version: '3'
services:
  maven:
    build:
      context: ./maven
      dockerfile: Dockerfile
    volumes:
      - sharevolume:/tmp/boxfuse-sample-java-war-hello/target/

  tomcat-service:
    build:
      context: ./tomcat
      dockerfile: Dockerfile  
    ports:
      - "8080:80"
    volumes:
      - sharevolume:/usr/local/tomcat/webapps/
    depends_on:
      - maven  
volumes:
  sharevolume: